### ISSUE TITLE
Komponentenart ändern (keine Auswahl)

### ISSUE THREAD

**Issue by Cete1337** [SigmaHyperon/biscuit#2]
Wenn keine Komponente ausgewählt ist und dann die Buttons gedrückt werden, wird man auf eine leere Seite geleitet.

**Comment by SigmaHyperon** [comment]
general issue on all lists
will have to come up with some error message to display

**Comment by SigmaHyperon** [comment]
fixed by preventing users from submiting the form with having nothing selected
