### ISSUE TITLE
Komponentenart löschen

### ISSUE THREAD

**Issue by Cete1337** [SigmaHyperon/biscuit#3]
Bei löschen einer Komponentanart kommt folgende Fehlermeldung:
Warning: Cannot modify header information - headers already sent by (output started at F:\Schule\xampp\htdocs\biscuit\src\php\fro_Auswahl.php:84) in F:\Schule\xampp\htdocs\biscuit\src\php\log_Auswahl.php on line 199

Es wird aber aus der Datenbank gelöscht.

**Comment by SigmaHyperon** [comment]
fixed
