### ISSUE TITLE
Komponenten löschen

### ISSUE THREAD

**Issue by Cete1337** [SigmaHyperon/biscuit#4]
Wenn eine Komponente gelöscht wird, kommt folgende Fehlermeldung:
An error occured!

Eintrag in der DB wird nicht gelöscht.

Schreibfehler in der Überschrift: Komponeten ;)

**Comment by SigmaHyperon** [comment]
unable to reproduce

**Comment by xE-motionx** [comment]
"Komponete" Gefixed :+1:

**Comment by SigmaHyperon** [comment]
closing due to this beeing intended behaviour
