### ISSUE TITLE
Geräte Art ändern (löschen)

### ISSUE THREAD

**Issue by Cete1337** [SigmaHyperon/biscuit#5]
Fehler:
Warning: Cannot modify header information - headers already sent by (output started at F:\Schule\xampp\htdocs\biscuit\src\php\fro_Auswahl.php:84) in F:\Schule\xampp\htdocs\biscuit\src\php\log_Auswahl.php on line 199

Eintrag wird aus DB gelöscht.

**Comment by SigmaHyperon** [comment]
fixed
