### ISSUE TITLE
Error Komponenten Details

### ISSUE THREAD

**Issue by Cete1337** [SigmaHyperon/biscuit#9]
Wenn bei Komponenten Details hinzugefügt werden und man dann auf "Ändern" geht, dann bekommt man folgenden Fehler:
Notice: Undefined index: komponenten_attribut_wert in F:\Schule\xampp\htdocs\biscuit\src\php\fro_Komponenten_aendern.php on line 88

**Comment by SigmaHyperon** [comment]
error in database 
pushed fix
